name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # THIS STEP CONVERTS YOUR NAME TO LOWERCASE
      - name: Lowercase the repo name
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Backend using the new lowercase variable
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}-backend:latest

      # Build Frontend using the new lowercase variable
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./minibank-ui
          file: ./minibank-ui/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}-ui:latest